services:
  - type: web
    name: art-assistant
    runtime: docker
    plan: free
    envVars:
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_APP_URL
        sync: false
      - key: SCOPES
        value: write_products
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: art-assistant-db
          property: connectionString

databases:
  - name: art-assistant-db
    databaseName: art_assistant
    user: art_assistant
    plan: free
    ipAllowList: []
